### get all
GET http://localhost:3100/user
Content-Type: */*

### get one by id
GET http://localhost:3100/user/1
Content-Type: */*

### create
POST http://localhost:3100/user
Content-Type: application/json

{
  "name": "book",
  "quantity": 23
}

### update
PATCH http://localhost:3100/user/23
Content-Type: application/json

{
  "quantity": 0
}

### delete
DELETE http://localhost:3100/user/23
Content-Type: application/json
