### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:3100/hello/world
Content-Type: */*

###
GET http://localhost:3100/product
Content-Type: */*

###
POST http://localhost:3100/product
Content-Type: application/json

{
  "name": "book",
  "quantity": 23
}

###
PATCH http://localhost:3100/product/23
Content-Type: application/json

{
  "quantity": 0
}