### get all
GET http://localhost:3100/user
Content-Type: */*

### get one by id
GET http://localhost:3100/user/73588ab3-1742-4d9f-ae87-d5edb946e9d6
Content-Type: */*

### create
POST http://localhost:3100/user
Content-Type: application/json

{
  "first_name": "dia",
  "last_name": "dia",
  "address": "Batam Center",
  "age": 30,
  "gender": "male",
  "email": "dia@email.com",
  "username": "diasiapa",
  "password": "password123"
}

### update
PATCH http://localhost:3100/user/2
Content-Type: application/json

{
  "gender": "female"
}

### delete
DELETE http://localhost:3100/user/7
Content-Type: application/json
